<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
    <AssemblyName>BIGA</AssemblyName>
    <Product>BIGA</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app_icon.png" />
    <Resource Include="Assets\app_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.5" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.59" />
  </ItemGroup>

</Project>
